### ISSUE TITLE
if process responding to crossbar_bindings:fold/2 process dies, validation still succeeds

### ISSUE THREAD

**Issue by aberke** [2600hz/kazoo#701]
Seems like there is work to be done around crossbar_bindings or kazoo_bindings.
Here's an issue I've run into:

For the validate_data step of (crossbar) api_util,
If a process responding to the "validate" event dies, then the validation successfully goes through.

**Comment by jamesaimonetti** [comment]
If a previous module in the chain is successful, it does appear to cause the whole fold to "succeed" because we ignore if modules crash during processing. The idea was that api_util sets the response status as 'failed' and only once a module successfully does its processing will the response status be updated. However, because we can't reset the response status in between module calls (accounts and users, for instance), if accounts succeeds but users crashes, the accounts' version of Context will be returned (with response status == 'success').

I suspect we could handle this a couple of different ways:

1. Change `kazoo_bindings:fold/2` to fail on matching module exceptions. I'm looking at the current places where `crossbar_bindings:fold/2` (which just wraps `kazoo_bindings`) and it seems like Crossbar can cleanup that behaviour in a number of places as well. I've started creating [tickets](https://2600hz.atlassian.net/browse/KAZOO-3230) about investigating this. If eliminated, changing `kazoo_bindings:fold/2` should be fine to do without impacting other modules.
2. Provide kazoo_bindings:fold/2 a list of options

    a. Provide a callback to run on Payload on exception could be a way for Crossbar/other apps to modify the behaviour as they see fit.
    b. Provide a flag to fail or continue on exception/error
    c. Provide a callback to execute on the Payload on each iteration of the fold (so Crossbar could reset the resp_status value of Context)

3. Initialize resp_status to 'undefined' before running the binding folds. In cb_context, only allow updating resp_status to 'success' if 'undefined'; if resp_status is 'error' or 'fail', don't allow the update. Then the Context will only be updated while not in a "failure" state.

I think we lean towards 3 at the moment, but happy to hear your thoughts on the above (or alternative ideas as well).

**Comment by aberke** [comment]
I agree with you and trust your judgement - thanks for taking this into account!
